---
- name: Install Chrony package
  package:
    name: chrony
    state: present

- name: Configure Chrony
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_file }}"
  notify:
    - restart chronyd

